### ISSUE TITLE
add total_rows to response of find API

### ISSUE THREAD

**Issue by chandu0101** [nolanlawson/pouchdb-find#19] opened 2015-03-22 14:55 UTC
haha sorry mate , i need this one again in find :) , could you please throw some pointers ..

**Comment by nolanlawson** [comment] 2015-03-22 16:10
I don't believe that find() implements it. The goal is to reproduce the Cloudant query language exactly, so if they don't support it, it's a no-go for pouchdb-find..  They might have something similar though.

**Comment by chandu0101** [comment] 2015-03-22 16:12
oh no! , what about pagination :s

**Comment by nolanlawson** [comment] 2015-03-22 16:54
Weird, I don't see anything in their API to support anything even remotely similar (e.g. `$count`). Maybe we should open up an issue on the CouchDB JIRA to start discussing this.

**Comment by chandu0101** [comment] 2015-03-23 14:54
created an issue https://issues.apache.org/jira/browse/COUCHDB-2644

**Comment by francescoagati** [comment] 2015-04-23 12:19
Hi,
i think that the time for processing the issue is very slow. Isn't possible expose this fields only for the local's query?

**Comment by standup75** [comment] 2015-05-18 20:35
+1

**Comment by moQuez** [comment] 2015-07-03 23:58
Apparently there is a fix already: https://github.com/apache/couchdb-mango/pull/6

**Comment by nolanlawson** [comment] 2015-07-12 22:56
Oh sweet. Looks like I can implement it now. :)

**Comment by nolanlawson** [comment] 2015-09-30 03:04
fixed by https://github.com/nolanlawson/pouchdb-find/commit/967e98114426bee524e0e1dfa321d73e218ba3b0

**Closed by nolanlawson** 2015-09-30 03:04 UTC
