### ISSUE TITLE
db.find give me this error

### ISSUE THREAD

**Issue by niktrix** [nolanlawson/pouchdb-find#60] opened 2015-09-28 12:09 UTC
Cannot use 'in' operator to search for 'startkey' in undefined

**Comment by nolanlawson** [comment] 2015-09-30 03:35
Can you provide a test to reproduce?

**Comment by Sturgelose** [comment] 2015-10-14 00:13
I'm having the same error. To reproduce, you can use:
Index
```
      db.createIndex({
        index: {
          fields: ['sectionId', 'contentType', 'date'],
          name: 'contentList',
          ddoc: 'contentList'
        }
      }).then(success).catch(error);
```

```
        db.find({
          selector: {
            sectionId: {$in: ['section1']},
            contentType: 'news'
          },
          //sort: ['date']
        }).then(function (result) {
          deferred.resolve(result)
        }).catch(function (err) {
          deferred.reject(err);
        });
```

**Comment by garrensmith** [comment] 2015-10-14 08:42
@Sturgelose You getting that error because you you haven't created a field that pouchdb-find can actually query against. The `$in` operator is an in memory filter. So first you need to have another field to search  with. 

So an example of this is

``` js
db.createIndex({
        index: {
          fields: ['contentType'],
          name: 'contentList',
          ddoc: 'contentList'
        }
      }).then(success).catch(error);

```

The query is then 

``` js
        db.find({
          selector: {
           contentType: "blogs",
            sectionId: {$in: ['section1']},
            contentType: 'news'
          },
          //sort: ['date']
        }).then(function (result) {
          deferred.resolve(result)
        }).catch(function (err) {
          deferred.reject(err);
        });
```

I would recommend reading on the condition operators in the [docs](https://docs.cloudant.com/cloudant_query.html)

I'm going to close this ticket since we don't have any test case to prove the initial error.

**Closed by garrensmith** 2015-10-14 08:42 UTC

**Comment by Sturgelose** [comment] 2015-10-16 15:31
Hi @garrensmith ,

I've been taking a look to the documentation and to the code you provided. Still I can't figure out the problem.

As a sidenote: the problem comes with the SectionId, which is an array of strings. If I disable that or I don't use an array, it works properly. If you check again the code I provided, the fields are already created (both sectionId and contentType, which are used in the find/query)

Any hint on this?

**Comment by garrensmith** [comment] 2015-10-16 17:36
@Sturgelose for this to query to work

```js
db.find({
          selector: {
            sectionId: {$in: ['section1']},
            contentType: 'news'
          },
          //sort: ['date']
        }).then(function (result) {
          deferred.resolve(result)
        }).catch(function (err) {
          deferred.reject(err);
        });
```

You need to create an index like this:

```js
db.createIndex({
        index: {
          fields: ['contentType'],
          name: 'contentList',
          ddoc: 'contentList'
        }
      }).then(success).catch(error);
```

**Comment by Sturgelose** [comment] 2015-10-17 09:03
Ok, I found the issue! (Did some debugging in the $in code you created)
Seems that in order to filter by $in, the object inside of the document must be an array. I was trying something strange because I always got the query result empty and didn't know the reason.

I was following the reference provided by MongoDB: http://docs.mongodb.org/manual/reference/operator/query/or/#or-versus-in
Where it says that you should use $in  instead of $or when you want to filter multiple equalities in the same field.

In pouchdb-find, the actual code rejects any field of the document for the $in filter in case it isn't an array... As I understand, it should allow filtering single values (non-array) and check if the value is any of the ones provided in the $in filter.

```
return fieldExists(doc) && docFieldValue instanceof Array; (line 1247)
```

**Comment by nolanlawson** [comment] 2015-10-18 00:00
I think we could have a friendlier error message for this, so I opened another issue: https://github.com/nolanlawson/pouchdb-find/issues/77

**Comment by nolanlawson** [comment] 2015-10-18 01:52
@Sturgelose would you like to contribute a fix? Seems like you found the place in the code to fix it; I'd really like to encourage other folks to contribute to this repo! :) All you would need is a test and a fix; you can refer to

**Comment by garrensmith** [comment] 2015-10-26 08:23
@Sturgelose this was a bug. $in now works on non-array fields. Thanks for the help.

**Comment by Sturgelose** [comment] 2015-10-26 08:25
@garrensmith , @nolanlawson , thanks for the fix :) And sorry if I couldn't do it myself but I've been really busy lately!
