### ISSUE TITLE
bug: db.find() not working on iOS

### ISSUE THREAD

**Issue by dwilt** [nolanlawson/pouchdb-find#143] opened 2016-01-12 00:30 UTC
In my Ionic application, getting this error:

```
TypeError: undefined is not an object (evaluating 'r.type')
callbackFromNativecordova.js:314
callbackFromNativecordova.js:313
(anonymous function)cordova.js:1108
nativeEvalAndFetchcordova.js:1116
nativeCallbackcordova.js:1105
(anonymous function)index.html:1
```
<img width="999" alt="screenshot 2016-01-11 16 27 09" src="https://cloud.githubusercontent.com/assets/1065539/12251002/3166f070-b880-11e5-863f-fd98a0e6121c.png">

This isn't happening though on desktop in Chrome. Here's my find:

```javascript
class MyClass {
    constructor() {
        this.db = new PouchDB('my-db');
    
        this.createParseIdIndex = this.db.createIndex({
            index: {
                fields: ['parseId']
            }
        }).catch(error => {
            console.log(error);
        });
    }
    getByParseId(parseId) {
        var createParseIdIndex = () => {
            return this.createParseIdIndex;
        };

        var find = () => {
            return this.db.find({
                selector: {
                    parseId: parseId
                }
            }).then(docs => docs.docs[0]);
        };

        return createParseIdIndex().then(find);
    }
```

**Comment by EuAndreh** [comment] 2016-01-12 15:45
Hmm, maybe the `selector` should look something like:
```javascript
return this.db.find({
  selector: {
    _id: parseId
  }
})...
```

**Comment by dwilt** [comment] 2016-01-12 16:22
@EuAndreh that's es6 shorthand. I updated the code. Sorry for the confusion. The problem still exists though.

**Comment by EuAndreh** [comment] 2016-01-12 17:52
Hmm, I see. 
What adapter are you using? SQLite?

**Comment by nolanlawson** [comment] 2016-01-15 02:05
This does look suspiciously like a SQLite Plugin bug due to the stacktrace.

**Comment by dwilt** [comment] 2016-01-15 02:10
@nolanlawson correct me if I'm wrong but Pouch will automatically use the SQL Plugin right? I mean, I guess we're using it and I may have set it up but I think it just used it by default? I'm not familiar with it that much. Hence the post ;)

**Comment by nolanlawson** [comment] 2016-01-15 02:27
[WebSQL](https://www.w3.org/TR/webdatabase/) !== [SQLite Plugin](https://github.com/litehelpers/Cordova-sqlite-storage)

But yes, if the SQLite Plugin is installed, then PouchDB will use it on iOS. Do you know which one you are using?

BTW if you really need the SQLite Plugin, you may want to look into https://github.com/nolanlawson/sqlite-plugin-fork, which is less likely to have bugs.

**Comment by dwilt** [comment] 2016-01-15 17:14
@nolanlawson how can I check which version of the SQLite Plugin I'm using (if at all)?. I believe we're using WebSQL because I get a notification in my console that says:

```javascript
PouchDB is downgrading "user-db" to WebSQL to avoid data loss, because it was already opened with WebSQL.   pouchdb.js:10489
PouchDB is downgrading "help-db" to WebSQL to avoid data loss, because it was already opened with WebSQL.   pouchdb.js:10489
PouchDB is downgrading "in-review-tours-db" to WebSQL to avoid data loss, because it was already opened with WebSQL.   pouchdb.js:10489
PouchDB is downgrading "draft-tours-db" to WebSQL to avoid data loss, because it was already opened with WebSQL.   pouchdb.js:10489 PouchDB is downgrading "user-db" to WebSQL to avoid data loss, because it was already opened with WebSQL.   pouchdb.js:10489
PouchDB is downgrading "help-db" to WebSQL to avoid data loss, because it was already opened with WebSQL.
```

**Comment by nolanlawson** [comment] 2016-01-16 19:35
Well, those messages are in place normally because of dirty browser data, so the best way to test is to completely clear out the data and try again (i.e. to experience what your users would experience). You may have to uninstall your app and reinstall it.

To check what you're using, you can do:

```js
db.info().then(console.log.bind(console));
```

If it says "`sqlite_plugin: true`", then you're using the SQLite Plugin.

**Comment by dwilt** [comment] 2016-01-19 03:00
@nolanlawson ok I'll try the data clear.. As for the db info:

```javascript
{
  adapter: "websql"
  auto_compaction: false
  db_name: "draft-tours-db"
  doc_count: 2
  sqlite_plugin: false
  update_seq: 191
  websql_encoding: "UTF-8"
}
```

**Comment by 5amfung** [comment] 2016-02-20 08:16
@dwilt Did it work after you cleared?

**Comment by nolanlawson** [comment] 2016-02-22 00:42
I'm going to close this, because this seems more like a Cordova issue than a PouchDB issue. The callstack you posted is clearly all `cordova.js`, so most likely that's where the issue is. If you could set a breakpoint there and figure out what `r.type` is and why it's undefined (maybe using unminified code would help?) then that would be helpful. Else I'm not sure how to reproduce.

**Closed by nolanlawson** 2016-02-22 00:42 UTC

**Comment by dwilt** [comment] 2016-02-22 01:04
Sounds good. Things are working correctly now. I don't think the clearing did it but I think updating my local Cordova did.
