### ISSUE TITLE
How to configure PouchDB-Find in a Ionic 2 project?

### ISSUE THREAD

**Issue by santclear** [nolanlawson/pouchdb-find#201] opened 2016-07-12 00:49 UTC
How to configure PouchDB-Find in a Ionic 2 project? In the following address is shown the configuration of PouchDB and it works: https://github.com/nolanlawson/pouchdb-ionic-2-typescript-demo. Best regards.

**Comment by nolanlawson** [comment] 2016-07-12 01:49
I'm not sure, sorry. Probably you need to follow similar steps to the steps for PouchDB, becase there are no up-to-date TypeScript bindings for pouchdb-find. Sorry about that.

**Comment by santclear** [comment] 2016-07-12 02:23
No problem, I would have knowledge to contribute. Unfortunately, I am newbie. I will try to work with Map/reducin and wait for a day is available. Thanks for the feedback.

**Comment by nolanlawson** [comment] 2016-07-12 15:18
Hey @santclear, I'm sorry to hear that. To be clear: neither PouchDB nor pouchb-find has up-to-date TypeScript definitions, so the whole challenge is just to use these libraries with `any` types so that TypeScript doesn't complain. Unfortunately I don't know TypeScript well enough to be able to advise how to do that.

Can you let me know what's unclear about the example code that makes it so you can use PouchDB but you can't use pouchdb-find? From glancing at it, it seems like the same steps for one should work for the other too.

**Comment by santclear** [comment] 2016-07-12 22:18
Before, sorry. My English is not very good. I want to correct what I said before. I do not have enough knowledge to contribute, as I am beginner. I will provide a minimized project that you should understand what I'm doing.

**Comment by santclear** [comment] 2016-07-13 00:05
Example code: [Screenshots](https://goo.gl/photos/zwKSmLQBLBgPqoAh9)
Best regards!

**Comment by nolanlawson** [comment] 2016-07-13 01:43
Nice, I see the error:

    Error TS2309: An export assignment cannot be used in a module with other exported elements.

Unfortunately I have no idea what to do. In normal ES6 you'd do:

```js
import PouchDB from 'pouchdb'
import PouchFind from 'pouchdb-find'
PouchDB.plugin(PouchFind)
```

I have no idea what TypeScript wants here, though.

**Comment by nolanlawson** [comment] 2016-07-13 01:45
Oh, I see what's going on here. It's because we're trying to be too clever with the `exports` object. We can fix this.

**Comment by nolanlawson** [comment] 2016-07-13 01:51
#202

**Comment by nolanlawson** [comment] 2016-07-13 01:59
More thorough explanation of what's happening here:

1. `exports` is assumed to be a normal JS object by CommonJS, so `exports.foo = 'bar'` is the same as `module.exports = {foo: 'bar'}`
2. TypeScript's ES6 module resolver does not support this pattern
3. `PouchDB.plugin(obj)` takes a normal JS object
4. So, any PouchDB plugins authored using this `exports.foo` style will fail to be imported by TypeScript.

**Comment by blakeembrey** [comment] 2016-07-13 03:04
@nolanlawson Sorry, I landed here through Twitter (Horse.js - https://twitter.com/horse_js/status/753051315358478337). I just wanted to quickly help out where I could though. Those manual definitions aren't entirely correct in TypeScript, they should be written as `const main: any; export = main`. This would make the import "any". That's because this module has no "default" export. To import this module in TypeScript, you need to do `import * as pouchdb from 'pouchdb'`.

The error you are seeing is because one of the definitions he tried to install succeeded. If you look at the reference just above this code, there's a `pouchdb` definition installed. The manually written definition conflicts on this line (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/pouchDB/pouch.d.ts#L225). You can not mix `export =` and other exports because `export =` has already defined in the export.

In this end, you shouldn't change anything in JavaScript. TypeScript definitions are purely compile-time.

**Comment by nolanlawson** [comment] 2016-07-13 03:08
@blakeembrey Thanks for hopping in! 😃 I think you're right; it looks like I totally misdiagnosed this error. Chalk it up to me knowing nothing about TypeScript, but foolishly trying to help out. So the issue here is mixing DT definitions with custom definitions, not with expecting `exports` to behave like an object?

**Comment by blakeembrey** [comment] 2016-07-13 03:12
Correct 😄 You can definitely mix two definition files together, you just can't mix those two different styles of exports because they fundamentally conflict - `export =` is meant to be the only export of a declaration, akin to `module.exports =` in CommonJS. This is supported by TypeScript because there's no alternative in ES6 where all imports are fundamentally treated like an object anyway (even `export default` is `exports.default`, not `module.exports` because that would mean mutating itself - though Babel does some trickery here, TypeScript does not). The ES6 style exports can be written in definitions, just not combined with `export =`.

By the way, I'm always happy to help out with TypeScript issues - feel free to ping me in the future 😄 If you ever want to get some definitions running locally, I'd be happy to provide some help there too.

**Comment by nolanlawson** [comment] 2016-07-13 03:29
Ahhh, that makes sense. Thanks! :) FWIW, I will probably try to merge https://github.com/nolanlawson/pouchdb-find/pull/202 anyway because I find the whole `exports.foo =` thing to be weird and unintuitive. Furthermore it looks like it would solve this particular issue, because in this case the default export (of a regular object) is actually the intended behavior.

**Comment by blakeembrey** [comment] 2016-07-13 03:46
@nolanlawson To quickly clarify (or maybe because I don't understand your last sentence), "default export" in this case is an ES6 construct (`export default`). TypeScript supports this as the `exports.default` property in CommonJS. For a module that does `module.exports = non_object_value`, it should be imported using the `import x = require('x')` syntax (E.g. CommonJS-exported functions are common of utilities). In this case, the change won't affect anything on TypeScript's side, so whatever you're happy with 😄 

TypeScript only cares about the definition side of things at compilation-time, but the definition side of things needs to match the JavaScript-side for everything to run smoothly. I find a lot of people think `export default` is the magical solution they need, but it's more often than not wrong. That was why I went to some effort above to say not to use `export default` in the definition, because it's also wrong here (this module does not have an ES6-compatible default export - which would be `exports.default`).

**Comment by blakeembrey** [comment] 2016-07-13 03:48
Since it's much easier to explain/demo in code, see http://www.typescriptlang.org/play/index.html#src=export%20default%20function%20()%20%7B%7D%0A%0Aexport%20function%20test%20()%20%7B%7D vs http://www.typescriptlang.org/play/index.html#src=function%20test%20()%20%7B%7D%0A%0Aexport%20%3D%20test

**Comment by blakeembrey** [comment] 2016-07-13 03:54
That's not to say you can't mix and match style of the definition when you're writing it youself though. You just need to match it back up. For example, see https://github.com/typed-typings/npm-content-type/blob/master/index.d.ts#L15-L17 and https://github.com/jshttp/content-type/blob/master/index.js#L54-L55 which would be how you'd also work with this library.

**Comment by santclear** [comment] 2016-07-13 04:02
Very thanks! I'm not in my house, I will check when I access my computer. 
It is very motivating to receive such care. This Framework is amazing!
Best regards!

**Comment by nolanlawson** [comment] 2016-07-13 15:25
@blakeembrey Sorry, I misunderstood because I had never seen `export = foo` or `import foo = require('foo')` before. Is this TypeScript-only? Is there a name for this module format?

When I said "default exports", yes, I was talking about `module.exports` in CommonJS. In any case, it looks like we're going to merge #202 which should hopefully make it clearer what the intended behavior is (which in ES6 would be expressed as `export default {foo: 'bar'}` and not `export var foo = 'bar'`).

I admit I'm still really confused about how TypeScript consumes different module patterns (the differences between `import * as foo from 'foo'` and `import foo from 'foo'` have tripped me up in the past as well), but maybe there's a good blog post or explainer that I can link people to if they run into these problems in the future?

**Comment by nolanlawson** [comment] 2016-07-13 15:27
Closing because #202 is merged, although we can still use this issue for discussion. @santclear You should be able to do this now:

```js
import * as PouchDB from 'pouchdb'
import * as PouchDBFind from 'pouchdb-find'
PouchDB.plugin(PouchDBFind)
```

^ This is the canonical way to use PouchDB + plugins from TypeScript.

**Closed by nolanlawson** 2016-07-13 15:27 UTC

**Comment by nolanlawson** [comment] 2016-07-13 15:33
@santclear This is fixed in pouchdb-find 0.10.3.

**Comment by santclear** [comment] 2016-07-13 16:08
@nolanlawson I can’t thank you enough, all of you are amazing! 
Later, I going to perform a test, when I arrive at home.
Best regards!

**Comment by blakeembrey** [comment] 2016-07-13 16:37
@nolanlawson Try https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Modules.md? It's generally pretty straight-forward - normal ES6 semantics (`export {}`/`import {}`, `export default`/`import x from`) but also has a backward-compatible CommonJS mode (`export = function`, `import x = require('x')`).

**Comment by santclear** [comment] 2016-07-14 00:18
Hello @nolanlawson unfortunately did not work. Follow the evidence [on the link](https://goo.gl/photos/DWvZjsJScV35CaGt9)

**Comment by blakeembrey** [comment] 2016-07-14 00:37
@santclear I tried to describe this for you above (see https://github.com/nolanlawson/pouchdb-find/issues/201#issuecomment-232242517). You need to patch the type definition in the way I described. Or you can use `typings install pouchdb-find=common~any` to do it for you.

**Comment by santclear** [comment] 2016-07-14 00:59
Sorry @blakeembrey, I had not understood before. Thank you for the feedback!
Now, I followed your suggestion. Even so, the error occurred, as shown in third image of the previous link.
When the plugin() method is called, the exception is thrown: Property plugin does not exist on type 'PouchDB'.
Best regards!

**Comment by blakeembrey** [comment] 2016-07-14 01:05
Thanks, sorry. The fix was correct for this library, but I overlooked it's a PouchDB definition issue. I'd guess the definition your using is out of date or incorrect. For instance, there's no `plugin` method in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/pouchDB/pouch.d.ts. It says in the header it's for 0.1, but PouchDB is on like v5 now, so it's well incorrect. I'd recommend you uninstall it and follow the same advice above until either you, or someone else, is able to correct type it.

**Comment by santclear** [comment] 2016-07-14 01:44
Sorry for my trouble @blakeembrey. See, if I understood. It is to reinstall PouchDB. Thus the plugin method will be available. Would it be this?
If it is that, Did not work.
These are the versions after new installation:
"pouchdb": "^5.4.5",
"pouchdb-find": "^0.10.3"

**Comment by blakeembrey** [comment] 2016-07-14 01:58
It's nothing to do with the JavaScript versions, it's the type definition you installed for PouchDB. Definitions and source code are independent here, and your error is a compilation error (caused by the definition) and not a run-time error (which would be caused by JavaScript).

**Comment by santclear** [comment] 2016-07-14 14:47
Got it. Thank @blakeembrey and @nolanlawson. For now, I will work with Map / Reducin. In parallel I'm going to study JS 6, PouchDB and typescript to soon contribute to your community.

**Comment by nolanlawson** [comment] 2016-07-14 15:13
Yeah, having out-of-date DefinitelyTyped definitions is almost worse than having no definitions, because it cases a lot of user confusion. There's been some work by the community to update the typings, but nothing shipped yet. Wondering if we'd be better off asking DT to just remove the defs.

**Comment by blakeembrey** [comment] 2016-07-14 18:37
Do you know if the PouchDB authors (or you also?) are willing to have definitions inline with the repository? It should be deleted from DefinitelyTyped until it's fixed, but perhaps PouchDB could also present an attractive alternative? I don't use it personally but I'm happy to help at a high level.

**Comment by nolanlawson** [comment] 2016-07-14 18:43
@blakeembrey We had some discussion in https://github.com/pouchdb/pouchdb/issues/5389 but ultimately decided against putting any definition files in the project itself. Our hope is that the TS community will rise to the occasion; we already have a #typescript channel in our Slack where it seems some work is getting done, although I'm not sure what the current status is.

**Comment by santclear** [comment] 2016-07-16 16:45
Solve!
@nolanlawson and @blakeembrey, Following his directions and with some research, I discovered how to work on a project Ionic 2 com PouchDB-Find. The sample project can be downloaded [here](https://github.com/santclear/ionic-pouchdb-friends)
Thank you for all!

**Comment by realappie** [comment] 2016-10-07 12:13
Nothing seems to be working with typescript 2.0, typings has been removed and Im wondering how I would use pouchdb-find with a typescript 2.0 (Ionic 2.0.0-RC0 project)

**Comment by vohtaski** [comment] 2016-10-07 12:43
Same here (problem with Ionic 2.0.0-RC0). I use this to require pouchdb:
```
import * as PouchDB from 'pouchdb';
import * as PouchFind from 'pouchdb-find';
PouchDB.plugin(PouchFind);
```
and get the following error:
```
[14:35:57]  Error: Module /Users/evgeny/app/node_modules/js-extend/extend.js does not export extend (imported by /Users/evgeny/app/node_modules/pouchdb/lib/index-browser.es.js)
    at Module.trace (/Users/evgeny/app/node_modules/rollup/dist/rollup.js:7706:29)
    at ModuleScope.findDeclaration (/Users/evgeny/app/node_modules/rollup/dist/rollup.js:7329:22)
    at Scope.findDeclaration (/Users/evgeny/app/node_modules/rollup/dist/rollup.js:5349:39)
    at Scope.findDeclaration (/Users/evgeny/app/node_modules/rollup/dist/rollup.js:5349:39)
    at CallExpression.bind (/Users/evgeny/app/node_modules/rollup/dist/rollup.js:5834:28)
    at /Users/evgeny/app/node_modules/rollup/dist/rollup.js:5149:50
    at VariableDeclarator.eachChild (/Users/evgeny/app/node_modules/rollup/dist/rollup.js:5166:5)
    at VariableDeclarator.bind (/Users/evgeny/app/node_modules/rollup/dist/rollup.js:5149:7)
    at /Users/evgeny/app/node_modules/rollup/dist/rollup.js:5149:50
    at VariableDeclaration.eachChild (/Users/evgeny/app/node_modules/rollup/dist/rollup.js:5163:19)
```

**Comment by vohtaski** [comment] 2016-10-07 12:48
pouchdb version: 6.0.6

**Comment by santclear** [comment] 2016-10-07 13:17
@realappie 
You should be working with Ionic to generate an application for mobile. You must use the SQLite 3, because in mobiles the indexed database will not work.
I abandoned my Ionic project. Initially I thought it would be possible to create a fully hybrid application, running on mobile and web. However, with the new update of Ionic RC.0 this is no longer possible.
You must make a decision. If your application is for Mobile you should use SQLite 3, but if web you can use the PouchDB. I for example, I migrated all my Ionic application Angular 2 + Material Design 2 + Bootstrap, and now I can easily use PouchDB with 'required'.

**Comment by realappie** [comment] 2016-10-07 13:48
@vohtaski Yeah Im getting really tired of that error, it makes me so angry the ionic team decided to switch rollupJS which is causing all of this chaos and drama. 

@santclear Why is it no longer possible? Is it because of a change in ionic it self or what is the main reason? 

![pouch db support table](http://image.prntscr.com/image/7984f16884334d6b95187c69d8c2e275.png)

**Comment by santclear** [comment] 2016-10-07 14:25
@realappie 
When an Ionic project is compiled and installed on the phone, the operating system will not use a browser. He will use the WebView, which does not support indexed database.
Before the RC.0, you could even import into your project the PouchDB, yet the indexed database only worked if the project was running on a web server. However after compile and install the mobile database indexed stopped working.
I do not know if it is by reason of the indexed database does not run on mobile phones, which led the Ionic developers have not paid attention to it. I recommend that you enter the Ionic forum and make those questioning.

**Comment by realappie** [comment] 2016-10-10 07:24
@santclear I think indexDB is supported by android 4.4 and up and iOS 8 and up.

**Comment by santclear** [comment] 2016-10-10 11:36
Ok, for some unknown reason, I could not run PouchDB in my mobile application. If you can, please share your knowledge with a sample application.

**Comment by realappie** [comment] 2016-10-10 13:47
@santclear Which android version are you running? Because android 4.4 & up stopped using crappy webview and uses the chromium engine.

**Comment by jlcarvalho** [comment] 2016-10-10 23:11
@realappie the problem isn't related with indexeddb. The bundle process of Ionic 2 changed in RC0.

@santclear this [repo](https://github.com/danbucholtz/ionic-third-party-lib-mega-test) uses PouchDB on RC0.

For more info see the issue https://github.com/driftyco/ionic/issues/8356.

**Comment by santclear** [comment] 2016-10-11 01:34
@jlcarvalho
Wow, it worked Ionic 2 RC.0 + PouchDB running on my Android! My previous statements were wrong. When I started researching what database to use in my application, some developers said they would not work. For fear I ended up not using.
Thank you very much!

**Comment by kabus202** [comment] 2016-10-13 18:34
@santclear can you explain what you did?

**Comment by tubauwe** [comment] 2016-10-13 19:32
I'm trying to solve nearly the same problem: Using Ionic 2 RC.0 + PouchDB + Crypto-Pouch as plugin. I managed to use PouchDB, but I have no luck to use Crypto-Pouch. I tried similar to [this repo ](https://github.com/matheusgarcez/ionic-2rc-pouchdb/)(mentioned by jlcarvalho), but get the following error in console:
`Uncaught TypeError: Cannot read property 'listenerCount' of undefined    _stream_readable.js:38`

**Comment by santclear** [comment] 2016-10-14 00:55
I said I could, with the help of @jlcarvalho use the Ionic 2 RC0 with pouchdb. I also tried to enable plugins, but I could not use :-(
I'm still trying, if anyone finds out before me, please share the knowledge with the community.

**Comment by vohtaski** [comment] 2016-10-14 14:08
thanks @jlcarvalho 
it's all working now

**Comment by santclear** [comment] 2016-10-15 21:42
@vohtaski
Besides Pouchdb, you could configure the plugins it? If so, please share how you did.

**Comment by imatefx** [comment] 2016-10-16 07:23
@tubauwe Did you manage to solve this error?
`Uncaught TypeError: Cannot read property 'listenerCount' of undefined _stream_readable.js:38
`

**Comment by tubauwe** [comment] 2016-10-16 20:29
No, I couldn't manage to solve this error until now.

**Comment by vohtaski** [comment] 2016-10-17 13:15
@santclear 

I use `pouchdb-find` plugin and it's working in the browser. Did not test yet on mobile app...

Require it like this:
``` typescript
import PouchDB from 'pouchdb-browser';
import PouchFind from 'pouchdb-find';
PouchDB.plugin(PouchFind);

export class Pouch {
  db: any;
  constructor() {

  init() {
    this.db = new PouchDB(`user`);

    this.db.find({
      selector: {name: "Tour"}
    }).then(function (result) {
      console.log(result);
    });
  }
```

package.json:
```json
  "config": {
    "ionic_rollup": "./rollup.config.js"
  },
```

And use a custom `rollup.config.js`. Basically, the important things are `useStrict: false` and added `namedExports` to solve the issue with a lib that pouchdb uses.
```js
var nodeResolve = require('rollup-plugin-node-resolve');
var commonjs = require('rollup-plugin-commonjs');
var globals = require('rollup-plugin-node-globals');
var builtins = require('rollup-plugin-node-builtins');
var json = require('rollup-plugin-json');


// https://github.com/rollup/rollup/wiki/JavaScript-API

var rollupConfig = {
  /**
   * entry: The bundle's starting point. This file will
   * be included, along with the minimum necessary code
   * from its dependencies
   */
  entry: 'src/app/main.dev.ts',

  /**
   * sourceMap: If true, a separate sourcemap file will
   * be created.
   */
  sourceMap: true,

  /**
   * format: The format of the generated bundle
   */
  format: 'iife',

  /**
   * dest: the output filename for the bundle in the buildDir
   */
  dest: 'main.js',

  useStrict: false,

  /**
   * plugins: Array of plugin objects, or a single plugin object.
   * See https://github.com/rollup/rollup/wiki/Plugins for more info.
   */
  plugins: [
    builtins(),
    commonjs({
        namedExports: {
            'node_modules/js-extend/extend.js': ['extend']
        }
    }),
    nodeResolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      extensions: ['.js']
    }),
    globals(),
    json()
  ]

};


if (process.env.IONIC_ENV == 'prod') {
  // production mode
  rollupConfig.entry = '{{TMP}}/app/main.prod.ts';
  rollupConfig.sourceMap = false;
}


module.exports = rollupConfig;
```

**Comment by santclear** [comment] 2016-10-17 13:26
Wow, very nice. My rollup settings were equal, but I was adding the plugin wrong.
I cranked up the plugin you wrote:

import pouch from 'pouchdb';
import pouchdbfind from 'pouchdb-find';
pouch.plugin (pouchdbfind);

Besides pouchdb-browser, pouchdb works only.

Now it's working! Thank @vohtaski

**Comment by tubauwe** [comment] 2016-10-19 19:49
In my code, I'm using 'import' instead of 'require' without any success. In my custom rollup.config.js is identical to the one mentioned above. But there's the again the following error:
`Uncaught TypeError: Cannot read property 'listenerCount' of undefined`

**Comment by hadrien-toma** [comment] 2016-10-22 18:58
In an Ionic 2 RC0 project, I tried the following code adapted from the answer of @vohtaski :
`import Pouchdb from 'pouchdb'`
`import PouchdbFind from 'pouchdb-find'`
`Pouchdb.plugin(PouchdbFind)`

I have a build success but the browser fails by giving this error :
`des.js:7 Uncaught TypeError: Cannot read property 'utils' of undefined(…)`

Any idea of what is going on?

**Comment by vohtaski** [comment] 2016-10-23 07:26
If I remember well, you should upgrade in your `package.json`
the `rollup-plugin-node-builtins` version as:
```
    "rollup-plugin-node-builtins": "^2.0.0",
```

**Comment by hadrien-toma** [comment] 2016-10-23 07:56
Thank you very much, it works!

**Comment by saniyusuf** [comment] 2016-10-23 14:34
Doing **typings install pouchdb-find=common~any** did the trick for me

**Comment by numerized** [comment] 2016-10-24 11:00
@saniyusuf superb way for Ionic Beta.

**Comment by nolanlawson** [comment] 2016-10-25 16:43
Is this working now or is there still work for pouchdb-find to do? I'm a bit confused from all this discussion. :confused:

**Comment by santclear** [comment] 2016-10-25 17:29
@nolanlawson 
I am using in my Ionic2 project RC.1 the PouchDB + PouchDB-Find. Both run both mobile and in the browser.
Who still have doubts, just check as configured [here](https://github.com/danbucholtz/ionic-third-party-lib-mega-test)
and import like this:
```
import PouchDB from 'pouchdb'
import PouchDBFind from 'pouchdb-find'
PouchDB.plugin (PouchDBFind)
```

**Comment by saniyusuf** [comment] 2016-10-25 18:17
@nolanlawson that worked for us without any extra addon .

**Comment by hadrien-toma** [comment] 2016-10-25 19:53
@nolanlawson : I tested the configuration given by @santclear and it also worked for me, without any special step.

**Comment by leetheguy** [comment] 2017-04-12 23:26
Regarding the post by saniyusuf:
I believe typings has been deprecated.
Definitely Typed is what all the cool kids are now using.
All together and the final answer (for now):

```
npm install --save pouchdb
npm install --save pouchdb-find
npm install --save-dev @types/pouchdb
npm install --save-dev @types/pouchdb-find
```

Then in your Component:

```
import PouchDB from 'pouchdb';
import PouchFind from 'pouchdb-find';
```
And in your constructor:

```
PouchDB.plugin(PouchFind);
```
