### ISSUE TITLE
$in maybe not working

### ISSUE THREAD

**Issue by t-knapp** [nolanlawson/pouchdb-find#240] opened 2017-01-09 16:32 UTC
Hello,

I have an Index over two fields. 
`localDB.createIndex({index: {fields: ['fieldName', 'value']}})`
This works. I can fetch documents that have a certain string value in fieldName and also in value:
`.localDB.find({selector: { fieldName: {$eq: "fieldNameValue"}, value: {$eq: argValueValue}}})`

In the next step I tried to use the $in operator to select all Documents with "fieldNameValue" in "fieldName and an value of "value" field in an array.

```
var arrayOfDesiredValues = ["DesieredString1", "DesieredString2"];
localDB.find({selector: { fieldName: {$eq: "fieldNameValue"}, value: {$in: arrayOfDesiredValues}}})
```
But this gives me that:

> Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'startkey' in undefined
    at getMultiFieldQueryOpts (pouchdb.find.js:2049)
    at getCoreQueryPlan (pouchdb.find.js:2095)
    at planQuery (pouchdb.find.js:2111)
    at pouchdb.find.js:1608

I browsed through the code and saw, that in `getMultiFieldCoreQueryPlan` no `$in` operator is defined. 

Do I have to use the $in operator in another way? Or is it not possible to select two fields (one of them with $in)? 

**Update** *2016-01-10*:
I also tried `selector: { $and : [{fieldName : {$eq : "fieldNameValue"}}, {value : {$in : arrayOfDesiredValues}}] }` but the error persists. Removing the `$and` operator and only using `{selector: {value: {$in: arrayOfDesiredValues}}}` works but gives a warning of no index defined for this field
> Object {docs: Array[3], warning: "no matching index found, create an index to optimize query time"}

But this index for field "value" is created: `localDB.createIndex({index: {fields: ['value'] } })`

Best regards
Tobias

**Comment by nolanlawson** [comment] 2017-01-11 16:32
This looks like a true bug, thank you for reporting! I will try to get to this when I have a chance, otherwise a PR would be appreciated. :)

**Comment by garrensmith** [comment] 2017-01-21 13:36
@t-knapp I have managed to reproduce the error. I will try and fix it as soon as possible. 

The fix for now is to make the index like this `localDB.createIndex({index: {fields: ['fieldName']}})`

**Comment by t-knapp** [comment] 2017-01-30 09:55
It was possible to modify the logic of filtering in that use-case. I fetch all documents with a specific value in the index field "fieldName" and do the "$in" operation in applications js-code. It is fast enough in this case.

**Comment by garrensmith** [comment] 2017-02-02 07:21
This should be fixed in the latest release. Could you verify for me and open this ticket again if it is not.

**Closed by garrensmith** 2017-02-02 07:21 UTC

**Comment by taxilian** [comment] 2017-04-04 05:50
I am experiencing this issue; trying to figure out what the latest release is to see if somehow I don't have it

**Comment by garrensmith** [comment] 2017-04-04 07:27
@taxilian we should be making a new release soon that fixes this
