### ISSUE TITLE
$or operator not working

### ISSUE THREAD

**Issue by marcelgoya** [nolanlawson/pouchdb-find#95] opened 2015-10-20 12:57 UTC
I've tried to use the $or operator with the latest build without success. I've compiled from the master branch, so I'm using the latest version. Below the code I've tried:

```javascript 
selector: {
	$and: [{
		$or: [{
			sender: window.userId
		}, {
			sender: '2ab73ef8-6d81-451c-9b48-188bb6217c3d'
		}]
	}, {
		$or: [{
			receiver: window.userId
		}, {
			receiver: '2ab73ef8-6d81-451c-9b48-188bb6217c3d'
		}]
	}]
}
```
and also 

```javascript 
selector: {
	$or: [{sender: window.userId}, {receiver: window.userId}]
}
```

It would be great if you could help me. 

Thanks,
Marcel

**Comment by marcelgoya** [comment] 2015-10-20 13:25
Error: couldn't find a usable index. try creating an index on: $or
    at createNoIndexFoundError (http://localhost:8100/lib/pouchdb-find/pouchdb.find-0.6.0.js:2077:10)
    at planQuery (http://localhost:8100/lib/pouchdb-find/pouchdb.find-0.6.0.js:2097:11)

**Comment by marcelgoya** [comment] 2015-10-20 13:35
I got working. thanks guys

**Comment by marcelgoya** [comment] 2015-10-20 15:31
I'm trying the following query but I'm getting an "couldn't find usable index" error message. I would appreciate if you could help me:

```javascript
$or: [{
						$and: [{
							"receiver": $scope.selectedChatFriendItem._id
						}, {
							"sender": window.userId
						}]
					}, {
						$and: [{
							"sender": $scope.selectedChatFriendItem._id
						}, {
							"receiver": window.userId
						}]
					}
				]```

Thanks,
Marcel

**Comment by viskin** [comment] 2015-10-20 15:57
I'm getting same error

**Comment by garrensmith** [comment] 2015-10-20 17:27
@marcelgoya this is not a bug with the `$or` operator. Your selector syntax is wrong. You need a field that pouchdb-find can query on __and__ then also an `$or` operator to also help filter. Also you don't need to do nested `$and`.

So without fully knowing your index or documents I would guess something like this:

``` js
selector: {
    $and: [
        sender: window.userId,
        receiver: window.userId,
        $or: [
            {  sender: '2ab73ef8-6d81-451c-9b48-188bb6217c3d'},
            {receiver: '2ab73ef8-6d81-451c-9b48-188bb6217c3d'}
        ]
      ]
}
```

**Comment by garrensmith** [comment] 2015-10-20 17:30
I'm going to close this since its not a bug in pouchdb-find.

**Closed by garrensmith** 2015-10-20 17:30 UTC

**Comment by marcelgoya** [comment] 2015-10-20 17:45
@garrensmith thanks for letting me know. Unfortunately the code you've suggested doesn't work. What I'm trying to do achieve is to get instant message objects where the fields are either (sender = 'abc' && receiver  = 'xyz') OR (receiver = 'abc' && sender = 'xyz'). I have spent a whole day trying to fix this problem. I am using the mongodb syntax but every time I'm running the query I am getting the index error message. Oh, and the indexes are there. I've triple checked it.

**Comment by garrensmith** [comment] 2015-10-20 17:47
Could you show what your createIndex looks like.

All misspelling thanks to my iPhone

**Comment by marcelgoya** [comment] 2015-10-20 17:50
No prob :) Sure, here it is 

````javascript

		localDB.createIndex({
			index: {
				name: 'user_sender',
				fields: ['user_sender']
			}
		});

		localDB.createIndex({
			index: {
				name: 'user_receiver',
				fields: ['user_receiver']
			}
		});

		localDB.createIndex({
			index: {
				name: 'is_received',
				fields: ['is_received']
			}
		});

		localDB.createIndex({
			index: {
				name: '_deleted',
				fields: ['_deleted']
			}
		});

		localDB.createIndex({
			index: {
				name: 'sender',
				fields: ['sender']
			}
		});

		localDB.createIndex({
			index: {
				name: 'receiver',
				fields: ['receiver']
			}
		});

		localDB.createIndex({
			index: {
				name: 'date_created',
				fields: ['date_created']
			}
		});
````

I had to create single indexes for each field because it didn't find the field when I tried to add all fields to a single index.

**Comment by garrensmith** [comment] 2015-10-21 08:40
@marcelgoya to get what you want you need to do 2 queries. One where `sender = 'abc' && receiver = 'xyz'` and another where `sender = 'xyz' && receiver = 'abc'`. Your index needs to be ['sender','receiver']

**Comment by marcelgoya** [comment] 2015-10-21 09:53
@garrensmith Hi Garren, thanks for letting me know.

**Comment by aelx311** [comment] 2015-11-04 16:10
I am having the same issue.

I created an index on 'statusId' like this:
```javascript
db.createIndex({
     index: {fields: ['statusId']},
     name: 'statusIdIndex',
     ddoc: 'statusIdDDoc'
})
```

I want to query documents with statusId of 2 or 5 or 6 like this:
```javascript
db.find({
    selector: {
        $or: [{statusId: {$eq:2}}, {statusId: {$eq:5}}, {statusId: {$eq:6}}]
    }
})
```

It is saying <b>Error: couldn't find a usable index. try creating an index on: $or</b>

What am I missing here? Thank you.
