### ISSUE TITLE
can't use index with $in

### ISSUE THREAD

**Issue by RaviBolla** [nolanlawson/pouchdb-find#176] opened 2016-04-19 10:14 UTC
I am using following code

                db.createIndex({
                    index: {
                        fields: ['name']
                    }
                }).then(function (result) {
                    return db.find({
                        "selector": { "name": { "$in": ['test', 'sample'] } },
                        "fields": ["name", "title"]
                    }).then(result => {
                        resolve(result);
                    }).catch(err => {
                        console.log(err);
                    });

I am getting following error.

Error: couldn't find a usable index. try creating an index on: name. Make sure that only $eq, $gt, $gte, $lt, and $lte are used for the indexed fields.

**Comment by nolanlawson** [comment] 2016-04-23 19:39
Unfortunately the `$in` selector is in-memory only. So to fix this, the best course would be to join two separate queries together using `$eq` instead. (Perhaps joined using `$or`, although I can't recall if that works or not. If not, you can also do two separate `find()s`.)

Closing because this is working as intended per Mango's API, although I admit it's not a great API choice and is terribly counter-intuitive and inefficient.

**Closed by nolanlawson** 2016-04-23 19:39 UTC
