### ISSUE TITLE
"Referer header required." error with .find

### ISSUE THREAD

**Issue by reggi** [nolanlawson/pouchdb-find#148] opened 2016-01-21 20:04 UTC
Trying to document my issue for others and myself. Here's the setup:

I have three documents in a `test` database.

<img width="548" alt="screen shot 2016-01-21 at 2 00 15 pm" src="https://cloud.githubusercontent.com/assets/296798/12492746/602030a6-c047-11e5-9cdd-bd476f3c6f0f.png">

Each looks like this:

```json
{
  "_id": "2",
  "_rev": "1-4a81943ac3816fb14645ea41f1babbaa",
  "cup": "mug",
  "drink": "scotch"
}
```

I'm trying to test out the find functionality and only want docs where `cup: "mug"`.

```js
testDB.find({
  selector: {cup: 'mug'},
  fields: ['_id', 'cup', 'drink'],
  sort: ['drink']
})
.then(console.log)
.catch(err => {
  console.log(err)
})
```

and it's giving me this error here:

```js
{ [bad_request: Something wrong with the request]
  status: 400,
  name: 'bad_request',
  message: 'Something wrong with the request',
  error: true,
  reason: 'Referer header required.' }
```

**Comment by reggi** [comment] 2016-01-21 20:08
Even when I create the index, I still get the error :)

```js
testDB.createIndex({
  index: {fields: ['cup']}
}).then(function () {
  return testDB.find({
    selector: {cup: 'mug'}
  })
})
.then(console.log)
.catch(err => {
  console.log(err)
})
```

**Comment by reggi** [comment] 2016-01-21 20:13
Oddly this is giving me an error as well:

```js
testDB.getIndexes()
.then(function (result) {
  console.log(result)
}).catch(function (err) {
  console.log(err)
});
``

```js
{ [not_found: missing]
  status: 404,
  name: 'not_found',
  message: 'missing',
  error: true,
  reason: 'missing' }
```

**Comment by reggi** [comment] 2016-01-21 20:21
This might be doup of https://github.com/nolanlawson/pouchdb-find/issues/103

**Comment by nolanlawson** [comment] 2016-01-21 20:55
What version of CouchDB are you using? `_find` is not supported in CouchDB 1.6.1 and below, although it will be released in CouchDB 1.7 and 2.0. It's also supported in PouchDB Server.

**Comment by nolanlawson** [comment] 2016-01-21 20:57
Yeah okay, I just tested locally and can confirm that the issue is the CouchDB version. We need better error messaging around this (and would gladly accept a PR that detected CouchDB's vague error messages and transformed it into something more useful! :smiley:). Sorry for the headaches.

**Closed by nolanlawson** 2016-01-21 20:57 UTC

**Comment by nolanlawson** [comment] 2016-01-21 20:58
BTW the easiest way to get started with CouchDB 2.x is:

```
docker run -d -p 3001:5984 klaemo/couchdb:2.0-dev \
  --with-haproxy --with-admin-party-please -n 1
```

Or pouchdb-server is just:

```
npm install -g pouchdb-server
pouchdb-server -p 5984
```

**Comment by reggi** [comment] 2016-01-21 21:47
:+1:
